### ISSUE TITLE
Citation module: Dependency & Full  are not working + bib text is not being downloaded

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdutilities.app#5] opened 2019-10-16 10:28 UTC
![image](https://user-images.githubusercontent.com/16609623/66911126-98814200-f018-11e9-9a29-088499337e72.png)

![image](https://user-images.githubusercontent.com/16609623/66911151-a3d46d80-f018-11e9-86d3-627779e712c3.png)

![image](https://user-images.githubusercontent.com/16609623/66910986-4cce9880-f018-11e9-87a4-511d62aaae2c.png)
![image](https://user-images.githubusercontent.com/16609623/66911255-cebec180-f018-11e9-8093-d85ae8570298.png)

**Comment by thiloshon** [comment] 2019-10-19 17:19
`Dependency & Full are not working` is not reproducible. bib text is not being downloaded is fixed with #7

**Comment by tom-gu** [comment] 2019-11-19 10:50
bib text is working :sunglasses:.

Citation for 'Dependency' and 'Full' are not working
I checked it in our binder env and in an Rstodio cloud project 
![image](https://user-images.githubusercontent.com/16609623/69140047-63aa5400-0aca-11ea-84e0-3bcf076c5331.png)

**Closed as completed** 2019-12-14 11:59 UTC
Labels: bug

**Comment by thiloshon** [comment] 2019-12-14 12:02
This is caused because of the new version of Shiny 1.4.0 having an backward incompatible function. 
https://stackoverflow.com/questions/58608109/text-to-be-written-must-be-a-length-one-character-vector.

This is fixed with #10
